name: Check Format

on:
  push:
    branches: [ 'release', 'development' ]
  pull_request:
    branches: [ 'release', 'development' ]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Gradle
        run: ./gradlew spotlessCheck