name: "Run Unit-Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Run Unit-Tests
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run test suites
        run: ./gradlew test --info

